[2023-03-31T03:08:19.553+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv4.postgres_to_s3_task manual__2023-03-31T03:08:17.275744+00:00 [queued]>
[2023-03-31T03:08:19.577+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv4.postgres_to_s3_task manual__2023-03-31T03:08:17.275744+00:00 [queued]>
[2023-03-31T03:08:19.577+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-31T03:08:19.578+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-31T03:08:19.578+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-31T03:08:19.624+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): postgres_to_s3_task> on 2023-03-31 03:08:17.275744+00:00
[2023-03-31T03:08:19.642+0000] {standard_task_runner.py:55} INFO - Started process 394 to run task
[2023-03-31T03:08:19.650+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv4', 'postgres_to_s3_task', 'manual__2023-03-31T03:08:17.275744+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/todays_games.py', '--cfg-path', '/tmp/tmpwtsh77bq']
[2023-03-31T03:08:19.650+0000] {standard_task_runner.py:83} INFO - Job 22: Subtask postgres_to_s3_task
[2023-03-31T03:08:19.823+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv4.postgres_to_s3_task manual__2023-03-31T03:08:17.275744+00:00 [running]> on host c73de31c854d
[2023-03-31T03:08:20.095+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv4
AIRFLOW_CTX_TASK_ID=postgres_to_s3_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-31T03:08:17.275744+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-31T03:08:17.275744+00:00
[2023-03-31T03:08:20.157+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/todays_games.py", line 48, in postgres_to_s3
    conn = hook.get_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 117, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2023-03-31T03:08:20.163+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv4, task_id=postgres_to_s3_task, execution_date=20230331T030817, start_date=20230331T030819, end_date=20230331T030820
[2023-03-31T03:08:20.182+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 22 for task postgres_to_s3_task (The conn_id `postgres_localhost` isn't defined; 394)
[2023-03-31T03:08:20.196+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-31T03:08:20.230+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
