[2023-05-07T17:38:41.805+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv2.call_standings manual__2023-05-07T17:38:36.197700+00:00 [queued]>
[2023-05-07T17:38:41.827+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv2.call_standings manual__2023-05-07T17:38:36.197700+00:00 [queued]>
[2023-05-07T17:38:41.827+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-07T17:38:41.828+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-05-07T17:38:41.828+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-07T17:38:41.868+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): call_standings> on 2023-05-07 17:38:36.197700+00:00
[2023-05-07T17:38:41.888+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv2', 'call_standings', 'manual__2023-05-07T17:38:36.197700+00:00', '--job-id', '1022', '--raw', '--subdir', 'DAGS_FOLDER/todays_gamesv2.py', '--cfg-path', '/tmp/tmpxv8a36gn']
[2023-05-07T17:38:41.876+0000] {standard_task_runner.py:55} INFO - Started process 475 to run task
[2023-05-07T17:38:41.899+0000] {standard_task_runner.py:83} INFO - Job 1022: Subtask call_standings
[2023-05-07T17:38:42.043+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv2.call_standings manual__2023-05-07T17:38:36.197700+00:00 [running]> on host f7ab54451666
[2023-05-07T17:38:42.192+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv2
AIRFLOW_CTX_TASK_ID=call_standings
AIRFLOW_CTX_EXECUTION_DATE=2023-05-07T17:38:36.197700+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-07T17:38:36.197700+00:00
[2023-05-07T17:38:42.371+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/todays_gamesv2.py", line 48, in _call_standings
    away_team = v['away_team']
KeyError: 'away_team'
[2023-05-07T17:38:42.379+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv2, task_id=call_standings, execution_date=20230507T173836, start_date=20230507T173841, end_date=20230507T173842
[2023-05-07T17:38:42.399+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1022 for task call_standings ('away_team'; 475)
[2023-05-07T17:38:42.435+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-07T17:38:42.460+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
