[2023-04-03T01:42:43.683+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv4.postgres_to_s3_task manual__2023-04-03T01:42:35.632233+00:00 [queued]>
[2023-04-03T01:42:43.693+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv4.postgres_to_s3_task manual__2023-04-03T01:42:35.632233+00:00 [queued]>
[2023-04-03T01:42:43.693+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-03T01:42:43.694+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-03T01:42:43.694+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-03T01:42:43.709+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): postgres_to_s3_task> on 2023-04-03 01:42:35.632233+00:00
[2023-04-03T01:42:43.715+0000] {standard_task_runner.py:55} INFO - Started process 152 to run task
[2023-04-03T01:42:43.722+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv4', 'postgres_to_s3_task', 'manual__2023-04-03T01:42:35.632233+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/todays_games.py', '--cfg-path', '/tmp/tmpjf3s5j04']
[2023-04-03T01:42:43.722+0000] {standard_task_runner.py:83} INFO - Job 51: Subtask postgres_to_s3_task
[2023-04-03T01:42:43.790+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv4.postgres_to_s3_task manual__2023-04-03T01:42:35.632233+00:00 [running]> on host bb4d827b1601
[2023-04-03T01:42:43.868+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv4
AIRFLOW_CTX_TASK_ID=postgres_to_s3_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-03T01:42:35.632233+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-03T01:42:35.632233+00:00
[2023-04-03T01:42:43.888+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/todays_games.py", line 50, in postgres_to_s3
    conn = hook.get_conn()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 117, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2023-04-03T01:42:43.894+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv4, task_id=postgres_to_s3_task, execution_date=20230403T014235, start_date=20230403T014243, end_date=20230403T014243
[2023-04-03T01:42:43.907+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 51 for task postgres_to_s3_task (The conn_id `postgres_localhost` isn't defined; 152)
[2023-04-03T01:42:43.930+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-03T01:42:43.952+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
