[2023-04-23T17:47:20.348+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv4.postgres_to_s3_task manual__2023-04-23T17:47:17.711239+00:00 [queued]>
[2023-04-23T17:47:20.370+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv4.postgres_to_s3_task manual__2023-04-23T17:47:17.711239+00:00 [queued]>
[2023-04-23T17:47:20.372+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T17:47:20.374+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-23T17:47:20.375+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-23T17:47:20.415+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): postgres_to_s3_task> on 2023-04-23 17:47:17.711239+00:00
[2023-04-23T17:47:20.423+0000] {standard_task_runner.py:55} INFO - Started process 491 to run task
[2023-04-23T17:47:20.440+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv4', 'postgres_to_s3_task', 'manual__2023-04-23T17:47:17.711239+00:00', '--job-id', '179', '--raw', '--subdir', 'DAGS_FOLDER/todays_games.py', '--cfg-path', '/tmp/tmpu_dlrda8']
[2023-04-23T17:47:20.441+0000] {standard_task_runner.py:83} INFO - Job 179: Subtask postgres_to_s3_task
[2023-04-23T17:47:20.560+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv4.postgres_to_s3_task manual__2023-04-23T17:47:17.711239+00:00 [running]> on host f789e77bc70a
[2023-04-23T17:47:20.699+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv4
AIRFLOW_CTX_TASK_ID=postgres_to_s3_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-23T17:47:17.711239+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-23T17:47:17.711239+00:00
[2023-04-23T17:47:20.717+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-04-23T17:47:20.728+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/todays_games.py", line 61, in postgres_to_s3
    cursor.execute('select * from test_table;')
psycopg2.errors.UndefinedTable: relation "test_table" does not exist
LINE 1: select * from test_table;
                      ^

[2023-04-23T17:47:20.760+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv4, task_id=postgres_to_s3_task, execution_date=20230423T174717, start_date=20230423T174720, end_date=20230423T174720
[2023-04-23T17:47:20.779+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 179 for task postgres_to_s3_task (relation "test_table" does not exist
LINE 1: select * from test_table;
                      ^
; 491)
[2023-04-23T17:47:20.823+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-23T17:47:20.865+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
