[2023-04-03T02:20:09.534+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv4.write_games_s3 manual__2023-04-03T02:20:05.953428+00:00 [queued]>
[2023-04-03T02:20:09.549+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv4.write_games_s3 manual__2023-04-03T02:20:05.953428+00:00 [queued]>
[2023-04-03T02:20:09.549+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-03T02:20:09.549+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-03T02:20:09.550+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-03T02:20:09.572+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): write_games_s3> on 2023-04-03 02:20:05.953428+00:00
[2023-04-03T02:20:09.578+0000] {standard_task_runner.py:55} INFO - Started process 994 to run task
[2023-04-03T02:20:09.592+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv4', 'write_games_s3', 'manual__2023-04-03T02:20:05.953428+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/todays_games.py', '--cfg-path', '/tmp/tmpv_48pifv']
[2023-04-03T02:20:09.593+0000] {standard_task_runner.py:83} INFO - Job 121: Subtask write_games_s3
[2023-04-03T02:20:09.732+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv4.write_games_s3 manual__2023-04-03T02:20:05.953428+00:00 [running]> on host bb4d827b1601
[2023-04-03T02:20:09.848+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv4
AIRFLOW_CTX_TASK_ID=write_games_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-04-03T02:20:05.953428+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-03T02:20:05.953428+00:00
[2023-04-03T02:20:09.862+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/todays_games.py", line 52, in write_games
    for k,v in games_data.items():
AttributeError: 'NoneType' object has no attribute 'items'
[2023-04-03T02:20:09.871+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv4, task_id=write_games_s3, execution_date=20230403T022005, start_date=20230403T022009, end_date=20230403T022009
[2023-04-03T02:20:09.884+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 121 for task write_games_s3 ('NoneType' object has no attribute 'items'; 994)
[2023-04-03T02:20:09.924+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-03T02:20:09.945+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
