[2023-04-03T01:42:38.717+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv4.write_games_s3 manual__2023-04-03T01:42:35.632233+00:00 [queued]>
[2023-04-03T01:42:38.727+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv4.write_games_s3 manual__2023-04-03T01:42:35.632233+00:00 [queued]>
[2023-04-03T01:42:38.727+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-03T01:42:38.728+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-03T01:42:38.728+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-03T01:42:38.745+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): write_games_s3> on 2023-04-03 01:42:35.632233+00:00
[2023-04-03T01:42:38.751+0000] {standard_task_runner.py:55} INFO - Started process 145 to run task
[2023-04-03T01:42:38.757+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv4', 'write_games_s3', 'manual__2023-04-03T01:42:35.632233+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/todays_games.py', '--cfg-path', '/tmp/tmpsknk_5no']
[2023-04-03T01:42:38.758+0000] {standard_task_runner.py:83} INFO - Job 48: Subtask write_games_s3
[2023-04-03T01:42:38.840+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv4.write_games_s3 manual__2023-04-03T01:42:35.632233+00:00 [running]> on host bb4d827b1601
[2023-04-03T01:42:38.986+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv4
AIRFLOW_CTX_TASK_ID=write_games_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-04-03T01:42:35.632233+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-03T01:42:35.632233+00:00
[2023-04-03T01:42:39.005+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/todays_games.py", line 43, in write_games
    for k,v in games_data.items():
AttributeError: 'NoneType' object has no attribute 'items'
[2023-04-03T01:42:39.027+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv4, task_id=write_games_s3, execution_date=20230403T014235, start_date=20230403T014238, end_date=20230403T014239
[2023-04-03T01:42:39.049+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 48 for task write_games_s3 ('NoneType' object has no attribute 'items'; 145)
[2023-04-03T01:42:39.096+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-03T01:42:39.118+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
