[2023-05-19T01:36:11.260+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv2.create_sql_table_task manual__2023-05-19T01:36:01.320432+00:00 [queued]>
[2023-05-19T01:36:11.273+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv2.create_sql_table_task manual__2023-05-19T01:36:01.320432+00:00 [queued]>
[2023-05-19T01:36:11.273+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-19T01:36:11.274+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-05-19T01:36:11.274+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-19T01:36:11.306+0000] {taskinstance.py:1303} INFO - Executing <Task(PostgresOperator): create_sql_table_task> on 2023-05-19 01:36:01.320432+00:00
[2023-05-19T01:36:11.313+0000] {standard_task_runner.py:55} INFO - Started process 9883 to run task
[2023-05-19T01:36:11.320+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv2', 'create_sql_table_task', 'manual__2023-05-19T01:36:01.320432+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/todays_gamesv2.py', '--cfg-path', '/tmp/tmpwebsdclz']
[2023-05-19T01:36:11.321+0000] {standard_task_runner.py:83} INFO - Job 22: Subtask create_sql_table_task
[2023-05-19T01:36:11.417+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv2.create_sql_table_task manual__2023-05-19T01:36:01.320432+00:00 [running]> on host a3bcfe770ad1
[2023-05-19T01:36:11.658+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv2
AIRFLOW_CTX_TASK_ID=create_sql_table_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-19T01:36:01.320432+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-19T01:36:01.320432+00:00
[2023-05-19T01:36:11.665+0000] {sql.py:254} INFO - Executing: 
        drop table if exists games;
        create table games (
            away_name VARCHAR(40),
            home_name VARCHAR(40),
            away_probable_pitcher VARCHAR(40),
            home_probable_pitcher VARCHAR(40),
            venue_name VARCHAR(40),
            game_date DATE,
            home_wins INT,
            home_losses INT,
            home_gb DECIMAL,
            away_wins INT,
            away_losses INT,
            away_gb DECIMAL,
            team_win_prob VARCHAR(4),
            game_time VARCHAR(9)
            );
    
[2023-05-19T01:36:11.719+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2023-05-19T01:36:11.724+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv2, task_id=create_sql_table_task, execution_date=20230519T013601, start_date=20230519T013611, end_date=20230519T013611
[2023-05-19T01:36:11.739+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 22 for task create_sql_table_task (The conn_id `postgres_localhost` isn't defined; 9883)
[2023-05-19T01:36:11.776+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-19T01:36:11.818+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
