[2023-03-31T03:13:32.388+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv4.write_games_s3 manual__2023-03-31T03:13:29.117518+00:00 [queued]>
[2023-03-31T03:13:32.432+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv4.write_games_s3 manual__2023-03-31T03:13:29.117518+00:00 [queued]>
[2023-03-31T03:13:32.433+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-31T03:13:32.434+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-31T03:13:32.434+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-31T03:13:32.491+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): write_games_s3> on 2023-03-31 03:13:29.117518+00:00
[2023-03-31T03:13:32.502+0000] {standard_task_runner.py:55} INFO - Started process 522 to run task
[2023-03-31T03:13:32.525+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv4', 'write_games_s3', 'manual__2023-03-31T03:13:29.117518+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/todays_games.py', '--cfg-path', '/tmp/tmp73u8_duq']
[2023-03-31T03:13:32.525+0000] {standard_task_runner.py:83} INFO - Job 33: Subtask write_games_s3
[2023-03-31T03:13:32.901+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv4.write_games_s3 manual__2023-03-31T03:13:29.117518+00:00 [running]> on host c73de31c854d
[2023-03-31T03:13:33.143+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv4
AIRFLOW_CTX_TASK_ID=write_games_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-03-31T03:13:29.117518+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-31T03:13:29.117518+00:00
[2023-03-31T03:13:33.173+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/todays_games.py", line 42, in write_games
    for k,v in games_data.items():
AttributeError: 'NoneType' object has no attribute 'items'
[2023-03-31T03:13:33.197+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv4, task_id=write_games_s3, execution_date=20230331T031329, start_date=20230331T031332, end_date=20230331T031333
[2023-03-31T03:13:33.243+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 33 for task write_games_s3 ('NoneType' object has no attribute 'items'; 522)
[2023-03-31T03:13:33.274+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-31T03:13:33.326+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
