[2023-04-03T01:55:36.874+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv4.create_sql_table_task manual__2023-04-03T01:55:30.424049+00:00 [queued]>
[2023-04-03T01:55:36.884+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv4.create_sql_table_task manual__2023-04-03T01:55:30.424049+00:00 [queued]>
[2023-04-03T01:55:36.885+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-03T01:55:36.885+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-03T01:55:36.885+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-03T01:55:36.902+0000] {taskinstance.py:1303} INFO - Executing <Task(PostgresOperator): create_sql_table_task> on 2023-04-03 01:55:30.424049+00:00
[2023-04-03T01:55:36.908+0000] {standard_task_runner.py:55} INFO - Started process 406 to run task
[2023-04-03T01:55:36.912+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv4', 'create_sql_table_task', 'manual__2023-04-03T01:55:30.424049+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/todays_games.py', '--cfg-path', '/tmp/tmpxiq1n_yl']
[2023-04-03T01:55:36.912+0000] {standard_task_runner.py:83} INFO - Job 55: Subtask create_sql_table_task
[2023-04-03T01:55:36.978+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv4.create_sql_table_task manual__2023-04-03T01:55:30.424049+00:00 [running]> on host bb4d827b1601
[2023-04-03T01:55:37.057+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv4
AIRFLOW_CTX_TASK_ID=create_sql_table_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-03T01:55:30.424049+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-03T01:55:30.424049+00:00
[2023-04-03T01:55:37.059+0000] {sql.py:254} INFO - Executing: 
        create or replace table games (
            game_datetime DATETIME,
            away_name VARCHAR(25),
            home_name VARCHAR(25),
            home_probable_pitcher VARCHAR(25),
            away_probable_pitcher VARCHAR(25),
            away_score INT,
            home_score INT,
            current_inning INT,
            inning_state VARCHAR(9),
            venue_name VARCHAR(25),
            series_status VARCHAR(15),
            summary VARCHAR(40)
        );
    
[2023-04-03T01:55:37.077+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_localhost` isn't defined
[2023-04-03T01:55:37.082+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv4, task_id=create_sql_table_task, execution_date=20230403T015530, start_date=20230403T015536, end_date=20230403T015537
[2023-04-03T01:55:37.094+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 55 for task create_sql_table_task (The conn_id `postgres_localhost` isn't defined; 406)
[2023-04-03T01:55:37.125+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-03T01:55:37.155+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
