[2023-05-21T22:05:03.955+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv3.create_sql_table_task manual__2023-05-21T22:04:50.345400+00:00 [queued]>
[2023-05-21T22:05:03.967+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv3.create_sql_table_task manual__2023-05-21T22:04:50.345400+00:00 [queued]>
[2023-05-21T22:05:03.968+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-21T22:05:03.968+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-05-21T22:05:03.971+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-21T22:05:03.993+0000] {taskinstance.py:1303} INFO - Executing <Task(PostgresOperator): create_sql_table_task> on 2023-05-21 22:04:50.345400+00:00
[2023-05-21T22:05:03.999+0000] {standard_task_runner.py:55} INFO - Started process 1373 to run task
[2023-05-21T22:05:04.006+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv3', 'create_sql_table_task', 'manual__2023-05-21T22:04:50.345400+00:00', '--job-id', '290', '--raw', '--subdir', 'DAGS_FOLDER/todays_gamesv3.py', '--cfg-path', '/tmp/tmp7sarfeek']
[2023-05-21T22:05:04.007+0000] {standard_task_runner.py:83} INFO - Job 290: Subtask create_sql_table_task
[2023-05-21T22:05:04.197+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv3.create_sql_table_task manual__2023-05-21T22:04:50.345400+00:00 [running]> on host b03c83f459ca
[2023-05-21T22:05:04.239+0000] {abstractoperator.py:615} ERROR - Exception rendering Jinja template for task 'create_sql_table_task', field 'sql'. Template: '~/***-docker/dags/include/create_table.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 659, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ~/airflow-docker/dags/include/create_table.sql
[2023-05-21T22:05:04.240+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1377, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1495, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2122, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 607, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 659, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ~/airflow-docker/dags/include/create_table.sql
[2023-05-21T22:05:04.253+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv3, task_id=create_sql_table_task, execution_date=20230521T220450, start_date=20230521T220503, end_date=20230521T220504
[2023-05-21T22:05:04.268+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 290 for task create_sql_table_task (~/airflow-docker/dags/include/create_table.sql; 1373)
[2023-05-21T22:05:04.302+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-21T22:05:04.355+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
