[2023-04-03T02:18:37.795+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv4.postgres_to_s3_task manual__2023-04-03T02:18:35.505432+00:00 [queued]>
[2023-04-03T02:18:37.806+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv4.postgres_to_s3_task manual__2023-04-03T02:18:35.505432+00:00 [queued]>
[2023-04-03T02:18:37.806+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-03T02:18:37.807+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-03T02:18:37.807+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-03T02:18:37.839+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): postgres_to_s3_task> on 2023-04-03 02:18:35.505432+00:00
[2023-04-03T02:18:37.846+0000] {standard_task_runner.py:55} INFO - Started process 933 to run task
[2023-04-03T02:18:37.860+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv4', 'postgres_to_s3_task', 'manual__2023-04-03T02:18:35.505432+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/todays_games.py', '--cfg-path', '/tmp/tmp7l59fjwe']
[2023-04-03T02:18:37.869+0000] {standard_task_runner.py:83} INFO - Job 106: Subtask postgres_to_s3_task
[2023-04-03T02:18:37.983+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv4.postgres_to_s3_task manual__2023-04-03T02:18:35.505432+00:00 [running]> on host bb4d827b1601
[2023-04-03T02:18:38.321+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv4
AIRFLOW_CTX_TASK_ID=postgres_to_s3_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-03T02:18:35.505432+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-03T02:18:35.505432+00:00
[2023-04-03T02:18:38.401+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-04-03T02:18:38.408+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/todays_games.py", line 61, in postgres_to_s3
    cursor.execute('select * from test_table;')
psycopg2.errors.UndefinedTable: relation "test_table" does not exist
LINE 1: select * from test_table;
                      ^

[2023-04-03T02:18:38.437+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv4, task_id=postgres_to_s3_task, execution_date=20230403T021835, start_date=20230403T021837, end_date=20230403T021838
[2023-04-03T02:18:38.502+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 106 for task postgres_to_s3_task (relation "test_table" does not exist
LINE 1: select * from test_table;
                      ^
; 933)
[2023-04-03T02:18:38.574+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-03T02:18:38.611+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
