[2023-03-31T03:06:32.197+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv4.write_games_s3 manual__2023-03-31T03:06:27.978845+00:00 [queued]>
[2023-03-31T03:06:32.261+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv4.write_games_s3 manual__2023-03-31T03:06:27.978845+00:00 [queued]>
[2023-03-31T03:06:32.265+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-31T03:06:32.268+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-31T03:06:32.268+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-31T03:06:32.365+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): write_games_s3> on 2023-03-31 03:06:27.978845+00:00
[2023-03-31T03:06:32.407+0000] {standard_task_runner.py:55} INFO - Started process 350 to run task
[2023-03-31T03:06:32.471+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv4', 'write_games_s3', 'manual__2023-03-31T03:06:27.978845+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/todays_games.py', '--cfg-path', '/tmp/tmp2avj1pts']
[2023-03-31T03:06:32.484+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask write_games_s3
[2023-03-31T03:06:32.769+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv4.write_games_s3 manual__2023-03-31T03:06:27.978845+00:00 [running]> on host c73de31c854d
[2023-03-31T03:06:33.091+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv4
AIRFLOW_CTX_TASK_ID=write_games_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-03-31T03:06:27.978845+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-31T03:06:27.978845+00:00
[2023-03-31T03:06:33.152+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/todays_games.py", line 41, in write_games
    for k,v in games_data.items():
AttributeError: 'NoneType' object has no attribute 'items'
[2023-03-31T03:06:33.188+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv4, task_id=write_games_s3, execution_date=20230331T030627, start_date=20230331T030632, end_date=20230331T030633
[2023-03-31T03:06:33.226+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 18 for task write_games_s3 ('NoneType' object has no attribute 'items'; 350)
[2023-03-31T03:06:33.268+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-31T03:06:33.319+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
